project: movement-s1-m1

sample_sheet: sample_sheet.csv

sampling_rate: 20_000 # Hz

filter:
  emg:
    drop_below: 400
    drop_above: 500
    scale: True
  vm:
    drop_below:
    drop_above:
    scale: False

movement:
  maxTimeApart: 0.1 # Events closer will be merged
  minLength: 0.2 # (s) Min event length
