project: movement-s1-m1
deploy_directory: docs

sample_sheet: sample_sheet.csv

sampling_rate: 20_000 # Hz

filter:
  emg:
    drop_below: 500
    drop_above: 1000
    scale: True
  vm:
    drop_below:
    drop_above:
    scale: False

detect:
  movement:
    maxTimeApart: 0.025 # (s) Events closer will be merged
    minLength: 0.1 # (s) Min event length
    percentile: 80
  rest:
    maxTimeApart: 0.0025 # (s) Events closer will be merged
    minLength: 0.1 # (s) Min event length
    percentile: 80
  ap:
    diffThreshold: 1.1
    minReachedVoltage: -25

report:
  author: Ieva Kerševičiūtė
  title: Movement in S1 and M1
  pages:
    - index
    - correlation
    - vm_S1_L23
    - vm_S1_L5
    - vm_M1_L23
    - vm_M1_L5
    - episodes_emg_S1_L23
    - episodes_emg_S1_L5
    - episodes_emg_M1_L23
    - episodes_emg_M1_L5
    - filtered_emg_S1_L23
    - filtered_emg_S1_L5
    - filtered_emg_M1_L23
    - filtered_emg_M1_L5
    - episodes_movement_vs_rest
    - filtered_movement_vs_rest
    - analysis_vm_dynamics
    - fft
  supplementary:
    - figure1.png
    - figure2.png
    - figure3.png
    - figure4.png
