```{r r_setup, include = FALSE}
# snakemake <- readRDS(".emg.Rmd.RDS")
snakemake@source("R/rmd_setup.R")
library(foreach)
library(data.table)
library(dplyr)
library(glue)
library(ggplot2)

config <- snakemake@config

scriptdir <- snakemake@scriptdir
region <- snakemake@wildcards$region

samples <- fread(snakemake@input$samples)
samples <- samples[ Region %in% region ]
```

---
date: <small>`r Sys.Date()`</small>
author: <small>`r config$report$author`</small>
title: `r config$report$title`
---

# Detection of movement episodes in `r gsub(region, pattern = "_", replacement = " ")` {.tabset .tabset-pills}

**Table 1.** Number of movement and rest episodes and their overall length in all the samples.
The _Overlaps_ column specifies whether there are any detected overlapping movement and rest episodes.

```{r, include = TRUE}
getSampleFile <- function(filelist, animalId, cellName) {
  files <- grep(pattern = glue("{animalId}/"), x = filelist, value = TRUE)
  files <- grep(pattern = glue("{cellName}/"), x = files, value = TRUE)

  stopifnot(length(files) == 1)

  files
}

episodes <- foreach(sid = samples[ , SID ], .combine = rbind) %do% {
  sample <- samples[ SID == sid ]

  fileMove <- getSampleFile(snakemake@input$movement, animalId = sample[ , AnimalID ], cellName = sample[ , CellName ])
  fileRest <- getSampleFile(snakemake@input$rest, animalId = sample[ , AnimalID ], cellName = sample[ , CellName ])

  move <- fread(fileMove)
  rest <- fread(fileRest)

  setkeyv(move, c("Start", "End"))
  setkeyv(rest, c("Start", "End"))

  nOverlaps <- foreach(channel = move[ , unique(Channel) ], .combine = rbind) %do% {
    foverlaps(
      rest[ Channel == channel ], move[ Channel == channel ]
    )
  } %>%
    # Exclude if overlap is only on the start/end time points
    .[ EventStart != i.EventEnd ] %>%
    .[ EventEnd != i.EventStart ] %>%
    na.omit() %>%
    nrow()

  rbind(
    fread(fileMove),
    fread(fileRest)
  ) %>%
    .[ , SID := sid ] %>%
    .[ , Overlaps := nOverlaps ]
}

counts <- episodes[ ,
  list(Count = .N, Time = round(sum(Length), 2)),
  by = list(SID, Movement)
]

overlaps <- episodes[ , list(Overlaps = unique(Overlaps)), by = SID ]

counts <- merge(
  counts[ Movement == TRUE ] %>%
    .[ , Movement := NULL ] %>%
    setnames(c("Count", "Time"), c("Movement", "TimeMovement")),
  counts[ Movement == FALSE ] %>%
    .[ , Movement := NULL ] %>%
    setnames(c("Count", "Time"), c("Rest", "TimeRest"))
) %>%
  merge(overlaps) %>%
  setcolorder(c("SID", "TimeMovement", "TimeRest")) %>%
  .[ ]

counts %>% showTable()
```

```{r results}
pages <- foreach::foreach(animalId = samples[ , AnimalID ], cellName = samples[ , CellName ]) %do% {
  knitr::knit_child(glue::glue("{snakemake@scriptdir}/reports/components/emg.Rmd"), quiet = TRUE, envir = environment())
}
```
```{r, include = TRUE, results = "asis"}
cat(unlist(pages), sep = "\n")
```
