```{r, include = FALSE}
# snakemake <- readRDS(".index.Rmd.RDS")
snakemake@source("R/rmd_setup.R")
library(data.table)
library(dplyr)
library(ggplot2)
library(ggpubr)

config <- snakemake@config

samples <- fread(snakemake@input$samples) %>%
  .[ , Count := NULL ] %>%
  .[ , Location := NULL ] %>%
  .[ , SID := NULL ] %>%
  .[ , Region := gsub(Region, pattern = "_", replacement = " ") ] %>%
  .[ , Region := gsub(Region, pattern = "23", replacement = "2/3") ] %>%
  .[ , Layer := gsub(Layer, pattern = "23", replacement = "2/3") ]
```

---
date: <small>`r Sys.Date()`</small>
author: <small>`r config$report$author`</small>
title: `r config$report$title`
---

# Project summary

## Study subjects

**Table 1.** Sample information.

```{r, include = TRUE}
samples %>%
  .[ , Depth := round(Depth, digits = 3) ] %>%
  setcolorder(c("AnimalID", "CellName", "Region", "Cortex", "Layer", "Date", "Depth")) %>%
  showTable()
```

<br></br>

```{r, include = TRUE, warning = FALSE, fig.height = 2.8}
p1 <- samples %>%
  ggplot(aes(x = Layer, y = Depth)) +
  geom_boxplot(linewidth = 0.25) +
  geom_jitter(aes(color = Cortex), width = 0.2, height = 0) +
  stat_compare_means(comparisons = list(c("L2/3", "L5")), size = 2.5, method = "t.test") +
  theme_light(base_size = 8) +
  theme(legend.position = "top") +
  theme(legend.margin = margin(0, 0, 0, 0)) +
  theme(legend.box.margin = margin(-5, 0, -5, 0)) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1)), trans = "reverse")

p2 <- samples %>%
  ggplot(aes(x = Cortex, y = Depth)) +
  geom_boxplot(linewidth = 0.25) +
  geom_jitter(aes(color = Layer), width = 0.2, height = 0) +
  stat_compare_means(comparisons = list(c("S1", "M1")), size = 2.5, method = "t.test") +
  theme_light(base_size = 8) +
  theme(legend.position = "top") +
  theme(legend.margin = margin(0, 0, 0, 0)) +
  theme(legend.box.margin = margin(-5, 0, -5, 0)) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1)), trans = "reverse")

p3 <- samples %>%
  ggplot(aes(x = Region, y = Depth)) +
  geom_boxplot(linewidth = 0.25) +
  geom_jitter(width = 0.2, height = 0) +
  stat_compare_means(
    comparisons = list(c("M1 L2/3", "S1 L2/3"), c("M1 L5", "S1 L5")),
    size = 2.5,
    method = "t.test"
  ) +
  theme_light(base_size = 8) +
  theme(legend.position = "top") +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1)), trans = "reverse")

ggarrange(
  p1, p2, p3,
  nrow = 1,
  widths = c(0.25, 0.25, 0.5),
  labels = letters[ 1:3 ],
  font.label = list(size = 9)
)
```

**Figure 1.** Cortical depth of recorded neurons, comparing **(a)** layers, **(b)** cortices,
and **(c)** regions. The differences between group means were evaluated using t-test.
