```{r, include = FALSE}
# snakemake <- readRDS(".vm.Rmd.RDS")
snakemake@source("R/rmd_setup.R")
library(foreach)
library(data.table)
library(dplyr)
library(glue)
library(ggplot2)

config <- snakemake@config

scriptdir <- snakemake@scriptdir
prefix <- snakemake@params$prefix
region <- snakemake@wildcards$region

samples <- fread(snakemake@input$samples)
samples <- samples[ Region %in% region ]

formatCortex <- ifelse(grepl(region, pattern = "S1"), "S1", "M1")
formatLayer <- ifelse(grepl(region, pattern = "L23"), "L2/3", "L5")

getSampleFile <- function(filelist, animalId, cellName) {
  files <- grep(pattern = glue("{animalId}/"), x = filelist, value = TRUE)
  files <- grep(pattern = glue("{cellName}/"), x = files, value = TRUE)

  stopifnot(length(files) == 1)

  files
}
```

---
date: <small>`r Sys.Date()`</small>
author: <small>`r config$report$author`</small>
title: `r config$report$title`
---

# Detection of action potentials in `r formatCortex` `r formatLayer` {.tabset .tabset-pills}

**Table 1.** Number of detected action potentials.

```{r, include = TRUE, warning = FALSE}
actionPotentials <- foreach(sid = samples[ , SID ], .combine = rbind) %do% {
  sample <- samples[ SID == sid ]

  filename <- getSampleFile(snakemake@input$action_potentials, sample[ , AnimalID ], sample[ , CellName ])

  fread(filename) %>%
    .[ , SID := sid ]
}

counts <- rbind(
  actionPotentials[ , list(Count = .N), by = SID ],
  data.table(SID = samples[ !(SID %in% actionPotentials[ , SID ]), SID ], Count = 0)
) %>%
  .[ match(samples[ , SID ], SID) ]

counts %>% showTable()
```

```{r results}
pages <- foreach::foreach(animalId = samples[ , AnimalID ], cellName = samples[ , CellName ]) %do% {
  knitr::knit_child(glue::glue("{snakemake@scriptdir}/reports/components/vm.Rmd"), quiet = TRUE, envir = environment())
}
```
```{r, include = TRUE, results = "asis"}
cat(unlist(pages), sep = "\n")
```

