## `r animalId` `r cellName` {.unlisted .unnumbered}

```{r}
data <- fread(getSampleFile(snakemake@input$emg_filter, animalId, cellName))
x <- as.matrix(data[ 2:nrow(data), 2:ncol(data) ])
rownames(x) <- data[ 2:nrow(data), V1 ]
time <- data.table(Index = colnames(data)[ 2:ncol(data) ]) %>%
  .[ , Time := seq(0, 10, 1 / 20000) ] %>%
  .[ ]

emgData <- x %>%
  reshape2::melt() %>%
  as.data.table() %>%
  setnames(c("Trial", "Index", "Value")) %>%
  merge(time, by = "Index") %>%
  .[ , Trial := factor(Trial, levels = data[ 2:nrow(data), V1 ]) ]

movement <- fread(getSampleFile(snakemake@input$movement, animalId, cellName)) %>%
  .[ , Trial := levels(emgData[ , Trial ])[ Channel + 1 ] ]

movementData <- foreach(i = seq_len(nrow(movement)), .combine = rbind) %do% {
  moveEpisode <- movement[ i ]
  emgData[ Trial == moveEpisode[ , Trial ] ] %>%
    .[ Time >= moveEpisode[ , Start ] ] %>%
    .[ Time <= moveEpisode[ , End ] ] %>%
    .[ , ID := moveEpisode[ , ID ] ]
}

rest <- fread(getSampleFile(snakemake@input$rest, animalId, cellName)) %>%
  .[ , Trial := levels(emgData[ , Trial ])[ Channel + 1 ] ]

restData <- foreach(i = seq_len(nrow(rest)), .combine = rbind) %do% {
  restEpisode <- rest[ i ]
  emgData[ Trial == restEpisode[ , Trial ] ] %>%
    .[ Time >= restEpisode[ , Start ] ] %>%
    .[ Time <= restEpisode[ , End ] ] %>%
    .[ , ID := restEpisode[ , ID ] ]
}
```

```{r, include = TRUE, fig.height = emgData[ , length(unique(Trial))] * 0.3 + 0.1}
p <- emgData %>%
  ggplot() +
  facet_wrap(~Trial, ncol = 1) +
  geom_line(aes(x = Time, y = Value), linewidth = 0.05) +
  theme_light(base_size = 8) +
  scale_x_continuous(limits = c(0, 10), expand = c(0, 0)) +
  theme(panel.spacing = unit(0, "lines")) +
  theme(strip.background = element_blank()) +
  theme(strip.text.x = element_blank()) +
  theme(panel.grid.minor = element_blank()) +
  theme(axis.text.y = element_blank()) +
  theme(axis.ticks.y = element_blank()) +
  ylab("")

# Only if there are detected movement episodes
if (nrow(movement) != 0) {
  p <- p + geom_line(data = movementData, aes(x = Time, y = Value, group = ID), linewidth = 0.25, color = "red")
}

# Only if there are detected rest episodes
if (nrow(rest) != 0) {
  p <- p + geom_line(data = restData, aes(x = Time, y = Value, group = ID), linewidth = 0.25, color = "blue")
}

p
```

**Figure 1.** All detected movement and rest episodes. Movement episodes are marked in **red**,
rest episodes are marked in **blue**.
